# This file should be copied to .github/workflows/build-agent.yml
name: Build Backup Agent

on:
  push:
    paths:
      - 'agent/**'
    branches: [develop, main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: agent
        run: npm install

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        working-directory: agent
        run: npm run build:win

      - name: Build Mac
        if: matrix.os == 'macos-latest'
        working-directory: agent
        run: npm run build:mac

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: homepinas-backup-${{ matrix.os }}
          path: |
            agent/build/dist/*.exe
            agent/build/dist/*.dmg
            agent/build/dist/*.yml
