#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Compiles HomePiNAS Image Builder to a standalone .exe file
.DESCRIPTION
    Uses PS2EXE to convert the PowerShell script into a native Windows executable.
    The resulting .exe is fully portable and doesn't require PowerShell knowledge to run.
.NOTES
    Run this script as Administrator to build the executable
#>

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "  ╔═══════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "  ║     HomePiNAS Image Builder - Compiler                    ║" -ForegroundColor Cyan
Write-Host "  ║     Creates standalone Windows executable                 ║" -ForegroundColor Cyan
Write-Host "  ╚═══════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

$scriptDir = $PSScriptRoot
$sourceScript = "$scriptDir\HomePiNAS-ImageBuilder.ps1"
$outputExe = "$scriptDir\HomePiNAS-ImageBuilder.exe"
$iconFile = "$scriptDir\icon.ico"

# Check source exists
if (-not (Test-Path $sourceScript)) {
    Write-Host "  [ERROR] No se encuentra HomePiNAS-ImageBuilder.ps1" -ForegroundColor Red
    exit 1
}

# Install PS2EXE if not present
Write-Host "  Verificando PS2EXE..." -ForegroundColor Yellow

$ps2exe = Get-Module -ListAvailable -Name ps2exe
if (-not $ps2exe) {
    Write-Host "  Instalando PS2EXE desde PowerShell Gallery..." -ForegroundColor Yellow
    try {
        Install-Module -Name ps2exe -Force -Scope CurrentUser -AllowClobber
        Write-Host "  PS2EXE instalado correctamente" -ForegroundColor Green
    } catch {
        Write-Host "  [ERROR] No se pudo instalar PS2EXE: $_" -ForegroundColor Red
        Write-Host ""
        Write-Host "  Instalalo manualmente con:" -ForegroundColor Yellow
        Write-Host "    Install-Module -Name ps2exe -Force -Scope CurrentUser" -ForegroundColor White
        exit 1
    }
}

Import-Module ps2exe -Force

# Create icon if not exists (extract from base64 in script)
if (-not (Test-Path $iconFile)) {
    Write-Host "  Creando icono..." -ForegroundColor Yellow

    # Simple blue raspberry icon in ICO format (base64)
    $iconBase64 = @"
AAABAAEAICAAAAEAIACoEAAAFgAAACgAAAAgAAAAQAAAAAEAIAAAAAAAABAAABMLAAATCwAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAABuA1R8bgNW/G4DVvxuA1WAbjNUAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAG4DVHxuA1f8bgNX/G4DV/xuA1f8bgNX/G4zVAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAHIDVHxyA1f8cgNX/HIDV/xyA1f8cgNX/HIDV/xyM1QAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB2A1R8dgNX/HYDV/x2A1f8dgNX/HYDV/x2A1f8dgNX/
HYzVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAegNUfHoDV/x6A1f8egNX/HoDV/x6A
1f8egNX/HoDV/x6A1f8ejNUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB+A1R8f
gNX/H4DV/x+A1f8fgNX/H4DV/x+A1f8fgNX/H4DV/x+A1f8fjNUAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAggNUfIIDV/yCA1f8ggNX/IIDV/yCA1f8ggNX/IIDV/yCA1f8ggNX/IIDV/yCM
1QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIYDU/yGA1P8hgNT/IYDU/yGA1P8hgNT/IYDU
/yGA1P8hgNT/IYDU/yGA1P8hjNQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIYDU/yKB
1P8igdT/IoHU/yKB1P8igdT/IoHU/yKB1P8igdT/IoHU/yKB1P8ijNQAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAjgdT/I4HU/yOB1P8jgdT/I4HU/yOB1P8jgdT/I4HU/yOB1P8jgdT/I4HU
/yOM1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACOB1P8kgtT/JILU/ySC1P8kgtT/JILU
/ySC1P8kgtT/JILU/ySC1P8kgtT/JIzUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJILU
/yWC1P8lgtT/JYLU/yWC1P8lgtT/JYLU/yWC1P8lgtT/JYLU/yWC1P8ljNQAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAJoLU/yaD1P8mg9T/JoPU/yaD1P8mg9T/JoPU/yaD1P8mg9T/JoPU
/yaD1P8mjNQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACmitQgpozU4KaM1OCmjNTg
pozU4KaM1OCmjNTgpozU4KaM1OCmjNTgpozU4KaR1CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0N
DQ8NDQ1vDQ0NfwsLC08AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7
g9ggO4bYoE2T2/9Nk9v/TZPb/02T2/9Nk9v/TZPb/02T2/9Nk9v/TZPb/02T2/9NmNugO4zYIAAA
AAAAAAAAAAAAAAAAAAANDQ0fDQ0N/w0NDf8NDQ3/DQ0N/w0NDZ8AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAO4PYIDuG2KBOlNz/TpTc/06U3P9OlNz/TpTc/06U3P9OlNz/TpTc
/06U3P9OlNz/TpncoD6M2CAAAAAAAAAAAAAAAAANDQ0PDQ0Njw0NDf8NDQ3/DQ0N/w0NDf8NDQ3/
DQ0Nzw0NDRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/htggP4nZoE+V3f9P
ld3/T5Xd/0+V3f9Pld3/T5Xd/0+V3f9Pld3/T5Xd/0+V3f9Pmt2gQozbIAAAAAAAAAAADQ0NDw0N
Dc8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDf8NDQ3/DQ0Nbw0NDQAAAAAAAAAAAAAAAAAAAAAAAAA7
g9YgPITWYDuE1p87hdegAAAAAAAAQYrZIEGM2aBQlt7/UJbe/1CW3v9Qlt7/UJbe/1CW3v9Qlt7/
UJbe/1CW3v9Qlt7/UJveoEOM2yAAAAAAAA0NDU8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDf8NDQ3/
DQ0N/w0NDf8NDQ2vAAAAAAAAAAAAAAAAAAAAAAAAAAAAO4PWoD2F1v89hdb/PobW/z6G1qBAjdkA
QYrZIEGN2qBRl9//UZff/1GX3/9Rl9//UZff/1GX3/9Rl9//UZff/1GX3/9Rl9//UZzfoEWN3CAA
AA0NDQ8NDQ3vDQ0N/w0NDf8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDf8NDQ3/DQ0NzwAAAAAAAA0N
DR8AAAAAAAAAAAAAAAA+htagPobW/z+H1/8/h9f/P4fX/z+H16BAjtkgQo3aoFKY4P9SmOD/Upjg
/1KY4P9SmOD/Upjg/1KY4P9SmOD/Upjg/1KY4P9Snd+gRo3cIA0NDU8NDQ3/DQ0N/w0NDf8NDQ3/
DQ0N/w0NDf8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDe8NDQ1PDQ0NHw0NDQAAAAAAAAAAAEGJ2CBB
jNmgQIfX/0CI1/9AiNf/QIjX/0CI16BDjdkgQ47boFOZ4f9TmeH/U5nh/1OZ4f9TmeH/U5nh/1OZ
4f9TmeH/U5nh/1OZ4f9Tnt+gSI7dIA0NDa8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N
/w0NDf8NDQ3/DQ0N/w0NDf8NDQ2/DQ0NTw0NDQAAAAAAAAAAAAAAAABBAAAARJDZIEGL2aBBiNj/
QYjY/0GI2P9BiNj/QYjYoESO2iBEj9ugVJri/1Sa4v9UmuL/VJri/1Sa4v9UmuL/VJri/1Sa4v9U
muL/VJri/1Se4KBJjt0gDQ0N3w0NDf8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0N
Df8NDQ3/DQ0N/w0NDd8NDQ1PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFE9kgRZDaoEKJ2f9Cidn/
QonZ/0KJ2f9CidmgRY/aIEWQ3KBVm+P/VZvj/1Wb4/9Vm+P/VZvj/1Wb4/9Vm+P/VZvj/1Wb4/9V
m+P/VaDgoEqP3SANDQ3vDQ0N/w0NDf8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0N
Df8NDQ3/DQ0Nzw0NDQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEUQ2SBGkdugQ4ra/0OK2v9Ditr/
Q4ra/0OK2qBGkNogRpHcoFac5P9WnOT/Vpzk/1ac5P9WnOT/Vpzk/1ac5P9WnOT/Vpzk/1ac5P9W
oeGgS5DeIA0NDd8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0N
Df8NDQ2PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEYR2SBHkdugRIvb/0SL2/9Ei9v/RIvb
/0SL26BHkNsgR5LdoFed5f9XneX/V53l/1ed5f9XneX/V53l/1ed5f9XneX/V53l/1ed5f9XouGg
TJDfIA0NDa8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDe8N
DQ0/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEYQ2SBHktugRYzc/0WM3P9FjNz/RYzc/0WM
3KBHkdsgSJPeoFie5v9Ynub/WJ7m/1ie5v9Ynub/WJ7m/1ie5v9Ynub/WJ7m/1ie5v9Yo+KgTZHf
IA0NDW8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDc8AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHD9kgSJPcoEaN3f9Gjd3/Ro3d/0aN3f9G
jd2gSJLcIEiT36BZn+f/WZ/n/1mf5/9Zn+f/WZ/n/1mf5/9Zn+f/WZ/n/1mf5/9Zn+f/WaTjoE6S
4CANDQ0fDQ0N3w0NDf8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDf8NDQ1fAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHD9kgSZTdoEeO3v9Hjt7/R47e
/0eO3v9Hjt6gSZPcIEmU4KBaoOj/WqDo/1qg6P9aoOj/WqDo/1qg6P9aoOj/WqDo/1qg6P9aoOj/
WqXkoE+S4QANDQ0ADQ0Njw0NDf8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDc8A
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASQ/ZIEmU3qBIj9//
SI/f/0iP3/9Ij9//SI/foEmU3SBJleGgW6Hp/1uh6f9boer/W6Hp/1uh6f9boen/W6Hp/1uh6f9b
oen/W6Hp/1um5aBQk+EgAAAAAAAAAAAADQ0NPw0NDe8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDf8N
DQ3/DQ0N/w0NDR8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AABKENkgSpXfoEmQ4P9JkOD/SZDg/0mQ4P9JkOCgSpXeIEuW4qBcoun/XKLq/1yi6v9cour/XKLq
/1yi6v9couv/XKLq/1yi6v9cour/XKfmoFGU4iAAAAAAAAAAAAAAAAANDQ0ADQ0Njw0NDf8NDQ3/
DQ0N/w0NDf8NDQ3/DQ0N/w0NDf8NDQ1PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7
g9cgO4XXML+828CmqfD/prD0/6aw9P+msPT/prD0/6aw9P+mr/P/pqft/6Wg5f+ln+X/paDl/6Wg
5f+loOX/paDl/6Wg5f+loOX/paDl/6Wg5f+lpuqgUpThIAAAAAAAAAAAAAAAAAAAAAANDQ0ADQ0N
Hw0NDa8NDQ3/DQ0N/w0NDf8NDQ3/DQ0N/w0NDY8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAA7g9egPIXX/7S06f+0t+z/tLfs/7S37P+0t+z/tLfs/7S37P+0t+z/tLfs/7S37P+0t+z/
tLfs/7S37P+0t+z/tLfs/7S37P+0t+z/tLfs/7O16aBSlOEgAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAADQ0NAA0NDR8NDQ2fDQ0N7w0NDf8NDQ3vDQ0NfwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAO4TXoDyF1/+0tun/tLfs/7S37P+0t+z/tLfs/7S37P+0t+z/tLfs/7S37P+0t+z/tLfs
/7S37P+0t+z/tLfs/7S37P+0t+z/tLfs/7S37P+ztumgU5XhIAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA0NDQANDQ0vDQ0Njw0NDa8NDQ1fAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAO4TXIDuF16C0tun/tLfs/7S37P+0t+z/tLfs/7S37P+0t+z/tLfs/7S37P+0
t+z/tLfs/7S37P+0t+z/tLfs/7S37P+0t+z/tLfs/7S37P+0tumgVJXhIAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA7hNcgO4TXoLO16f+0t+z/tLfs/7S37P+0t+z/tLfs/7S37P+0
t+z/tLfs/7S37P+0t+z/tLfs/7S37P+0t+z/tLfs/7S37P+0t+z/s7bpoFSV4SAAAAAAAAAAAAA7
g9cfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0N
DRAAAAAAAAAAAAAAAAAAAAAAAAA7hNcgO4XXoLS26f+0t+z/tLfs/7S37P+0t+z/tLfs/7S37P+0
t+z/tLfs/7S37P+0t+z/tLfs/7S37P+0t+z/tLfs/7S37P+0t+z/tLbpoFWW4iAAAAAAAAAAAA0N
DRANDTYwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAO4TXIDuF16C0tun/tLfs/7S37P+0t+z/tLfs/7S37P+0t+z/tLfs
/7S37P+0t+z/tLfs/7S37P+0t+z/tLfs/7S37P+0t+z/tLfs/7O26aBVluIgAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA7hNcgPIXXn7S26f+0t+z/tLfs/7S37P+0t+z/tLfs/7S37P+0t+z/
tLfs/7S37P+0t+z/tLfs/7S37P+0t+z/tLfs/7S37P+0t+z/s7Xpn1aV4iAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAADuE1yA7hdZgtLXo4LS26f+0tun/tLbp/7S26f+0tun/tLbp/7S26f+0
tun/tLbp/7S26f+0tun/tLbp/7S26f+0tun/tLbp/7S26OCzteiAV5biIAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//wAAP/wAAD/wAAAf4AAAD8AAAAfAAAADwAAAAcA
AAADAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAB4AADweAAD8fgAD/v4AB/
/+AA///wAf//+Af///wf//////8=
"@

    $iconBytes = [Convert]::FromBase64String($iconBase64)
    [System.IO.File]::WriteAllBytes($iconFile, $iconBytes)
    Write-Host "  Icono creado" -ForegroundColor Green
}

# Compile to executable
Write-Host ""
Write-Host "  Compilando a ejecutable..." -ForegroundColor Yellow
Write-Host ""

$params = @{
    InputFile  = $sourceScript
    OutputFile = $outputExe
    NoConsole  = $true
    RequireAdmin = $true
    Title      = "HomePiNAS Image Builder"
    Description = "Creates customized Raspberry Pi OS images with HomePiNAS"
    Company    = "Homelabs.club"
    Product    = "HomePiNAS Image Builder"
    Version    = "2.0.0.0"
    Copyright  = "Homelabs.club 2024"
}

if (Test-Path $iconFile) {
    $params.IconFile = $iconFile
}

try {
    Invoke-PS2EXE @params

    if (Test-Path $outputExe) {
        Write-Host ""
        Write-Host "  ╔═══════════════════════════════════════════════════════════╗" -ForegroundColor Green
        Write-Host "  ║        COMPILACION EXITOSA                                ║" -ForegroundColor Green
        Write-Host "  ╚═══════════════════════════════════════════════════════════╝" -ForegroundColor Green
        Write-Host ""
        Write-Host "  Ejecutable creado:" -ForegroundColor White
        Write-Host "  $outputExe" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "  Este archivo es completamente portable." -ForegroundColor Yellow
        Write-Host "  Distribuyelo sin necesidad de archivos adicionales." -ForegroundColor Yellow
        Write-Host ""
    }
} catch {
    Write-Host ""
    Write-Host "  [ERROR] Fallo la compilacion: $_" -ForegroundColor Red
    exit 1
}
